Repository markdwags/Razor, pull requests merged in 2020-02, with the labels that each got.

#70 Disposes systray icon after exit
  Razor/UI/Razor.cs
Labels: bug

#71 fix discord overlay system access violation crash
  Razor/UI/Razor.cs
Labels: classicuo

#75 add attack command to razor script
  FastColoredTextBox/SyntaxHighlighter.cs
  Razor/Scripts/Commands.cs
  Razor/Scripts/ScriptManager.cs
Labels: enhancement
